### ISSUE TITLE
Add eluvio-live object to tenant

### ISSUE THREAD

**Issue by elv-serban** [eluv-io/elv-live-js#132]
### Background

The tenant contract has an associated content fabric object.  Use the content fabric object metadata to store special services information (information that is needed by applications or content fabric itself but not needed on chain).

#### Tenant provisioning

When creating the Eluvio Live object for this tenant, also add it to the tenant fabric metadata:

```
{
  "public": {
    "eluvio_live_id": "iq__3UrZaAFZgoBkDLuuDuesqY5rQZy5",
  }
}
```
There is a function that sets this metadata field already `TenantSetEluvioLiveId()`

#### Tenant show

Show a 'Services' section:
```
services
  - eluvio_live_id:  iq__3UrZaAFZgoBkDLuuDuesqY5rQZy5
```
(currently we only store information for one service but there may be multiple in the future)

Add option `elv-admin tenant show` `--show_metadata`:
- retrieve and display the metadata of the fabric object (could be converted to yaml to match the current output)

**Comment by elv-Noppapon** [comment]
Will be merged into the new tenant show PR: https://github.com/elv-Noppapon/elv-live-js/pull/1

**Comment by elv-Noppapon** [comment]
Merged to branch tenant in [PR](https://github.com/eluv-io/elv-live-js/pull/124)
