### ISSUE TITLE
Tenant provisioning "checker"

### ISSUE THREAD

**Issue by elv-michelle** [eluv-io/elv-live-js#48]
This issue outlines a set of requirements for a tenant provisioning "checker" or verification within elv-live-js (to be completed).

- Check tenant contract
-- Check tenant contract version / and is a tenant contract
- Verify tenant admins group
-- Determine root address and verify that root key is the owner of the tenant contract, groups
- Verify media platform
-- Should have all libraries and content types as created by the tenant init script
- Verify eluvio live
-- Verify minter, mint helper and authd key is a tenant admin

**Comment by elv-serban** [comment]
This functionality is now available:

```
./elv-admin tenant_show <iten>
```

```
./elv-live tenant_show <iten>
```
