### ISSUE TITLE
Tenant provisioning

### ISSUE THREAD

**Issue by elv-todd** [eluv-io/elv-live-js#53]
We'd like an automated CLI for tenant provisioning.  one major issue with the existing flow is the tenant is made late in the process.

see `tenant_overview.svg` in https://github.com/qluvio/info/blob/master/content_fabric/tenant_overview.svg

Four steps:

1) create tenant root key, fund it, create wallet contact

2) create contract / admins group

3) call existing TenantProvisioning js, refactored out (media platform, eluvio live / nfts)
  -- create common 'content types'
  -- create common 'libraries'
 
4) provision 'nft authority'
  -- minter, proxy owner
  -- future work: make and use API in authd -- when creating NFT contact, don't use tenant key / root key; use an NFT author key instead   [file as separate issue]

existing docs: http://docs.elv/setup/tenant_setup/
config info: https://github.com/qluvio/ops/wiki/Tenants-955305

**Comment by elv-Todd** [comment]
also discussed the site updates push -- 
- POST /int {hash}
- validator can run before update

**Comment by elv-todd** [comment]
also discussed...

- make NFT Templates Content Library, move out of Title Mezzanines?
- app to create NFT Templates?

**Comment by elv-serban** [comment]
- add consumer group for tenant (equivalent to elvmastercli tenant modify add-consumers)
- set abr profile JSON in library metadata  (Title Mezzanines, NFT Templates)
- set DRM info (cert) in library metadata   (Title Mezzanines, NFT Templates)
