### ISSUE TITLE
tenant_wallets seems to return invalid yaml

### ISSUE THREAD

**Issue by PushEngineering** [eluv-io/elv-live-js#81]
If I issue a command thus:

`./elv-live tenant_wallets iten2dxxxxxxxxxxxiNb6J > ./foo.yaml`

The returned `foo.yaml` file has the first few lines as follow:

```
% head -4 foo.yaml
Tenant wallets tenant: iten2dbu685wiHLyjgLnx19jEKxiNb6J max_results: undefined
Network: main
contents:
  - addr: '0x18cc5c4dae32307fcc57c5cb882296447efd10e4'
```

That first line (`Tenant wallets tenant....`)  is not valid yaml - so i have to remove it before i can pass it to (say) `yq`...

It just seems the command name is somehow being emiited to stdout.

**Comment by elv-serban** [comment]
Fixed by https://github.com/eluv-io/elv-live-js/pull/165
